swagger: "2.0"
info:
  title: mySampleAPI
  description: API Walk through.
  version: 1.0.0

host: myapi2.apigateway.coe453-assignment-1.cloud.goog
basePath: /
schemes:
  - https
  - http

paths:
  /add:
    post:
      operationId: add
      summary: Addition operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://runadd-grbzwajuja-uc.a.run.app
  /sub:
    post:
      operationId: sub
      summary: Subtraction operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://runsub-grbzwajuja-uc.a.run.app
  /div:
    post:
      operationId: div
      summary: Division operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://rundiv-grbzwajuja-uc.a.run.app
  /mul:
    post:
      operationId: mul
      summary: Multiplication operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://runmul-grbzwajuja-uc.a.run.app
