swagger: "2.0"
info:
  title: mySampleAPI
  description: API Walk through.
  version: 1.0.0

host: myapi.apigateway.coe453-assignment-1.cloud.goog
basePath: /
schemes:
  - https
  - http

paths:
  /add:
    post:
      operationId: add
      summary: Add operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-coe453-assignment-1.cloudfunctions.net/add
  /sub:
    post:
      operationId: sub
      summary: Add operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-coe453-assignment-1.cloudfunctions.net/sub
  /div:
    post:
      operationId: div
      summary: Add operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-coe453-assignment-1.cloudfunctions.net/div
  /mul:
    post:
      operationId: mul
      summary: Add operation with API
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-coe453-assignment-1.cloudfunctions.net/mul
